//! MELPA package-install integration tests.
//!
//! Every test installs a real package from MELPA through neomacs's OWN
//! `package-install` — exactly like a user running `M-x package-install` or
//! `use-package :ensure` — then exercises the installed package. Nothing is
//! fetched or staged from Rust: `package.el` does the archive refresh,
//! transitive dependency resolution, download, autoload generation,
//! byte-compilation, and activation, and we assert the result matches what GNU
//! Emacs produces.
//!
//! These require network access and are `#[ignore]`d so the default suite stays
//! offline. Run them with:
//!   `cargo nextest run -p neomacs-melpa-tests --run-ignored all`

use neomacs_melpa_tests::*;

const NET: &str = "network: installs a real package from MELPA via package-install";

#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn install_dash_and_use_map() {
    let out = install_and_eval(
        &["dash"],
        r#"(require 'dash)
  (unless (equal (-map (lambda (n) (* n 2)) '(1 2 3 4)) '(2 4 6 8))
    (error "dash -map mismatch"))
  (unless (equal (-mapcat (lambda (x) (list x x)) '(1 2 3)) '(1 1 2 2 3 3))
    (error "dash -mapcat mismatch"))
  (princ "DASH-OK")"#,
    )
    .expect("install + use dash");
    assert!(out.contains("DASH-OK"), "stdout:\n{out}");
}

#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn install_s_and_use_string_ops() {
    let out = install_and_eval(
        &["s"],
        r#"(require 's)
  (unless (string= (s-trim "  hello  ") "hello") (error "s-trim"))
  (unless (string= (s-trim-left "  hello") "hello") (error "s-trim-left"))
  (unless (string= (s-trim-right "hello  ") "hello") (error "s-trim-right"))
  (unless (equal (s-split "," "a,b,c") '("a" "b" "c")) (error "s-split"))
  (unless (s-contains? "lo" "hello") (error "s-contains?"))
  (unless (string= (s-replace "world" "emacs" "hello world") "hello emacs") (error "s-replace"))
  (unless (string= (s-upcase "hello") "HELLO") (error "s-upcase"))
  (unless (= (s-count-matches "o" "foo boo") 4) (error "s-count-matches"))
  (princ "S-OK")"#,
    )
    .expect("install + use s");
    assert!(out.contains("S-OK"), "stdout:\n{out}");
}

/// `package-install` must resolve and install transitive dependencies (hydra
/// depends on lv), exactly like GNU Emacs.
#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn install_hydra_resolves_lv_dependency_and_defhydra_works() {
    let out = install_and_eval(
        &["hydra"],
        r#"(unless (assq 'lv package-alist)
    (error "hydra dependency lv was not auto-installed"))
  (require 'hydra)
  (unless (fboundp 'defhydra) (error "defhydra not defined"))
  (defhydra hydra-test () "test" ("a" (lambda () (interactive))))
  (unless (fboundp 'hydra-test/body) (error "defhydra did not define hydra-test/body"))
  (princ "HYDRA-OK")"#,
    )
    .expect("install hydra + resolve lv dep");
    assert!(out.contains("HYDRA-OK"), "stdout:\n{out}");
}

#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn install_use_package_resolves_bind_key_dependency() {
    let out = install_and_eval(
        &["use-package"],
        r#"(require 'use-package)
  (unless (fboundp 'use-package) (error "use-package macro not defined"))
  (unless (fboundp 'bind-key) (error "bind-key dependency not available"))
  (princ "USE-PACKAGE-OK")"#,
    )
    .expect("install use-package + bind-key dep");
    assert!(out.contains("USE-PACKAGE-OK"), "stdout:\n{out}");
}

#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn install_ivy_and_mode_available() {
    let out = install_and_eval(
        &["ivy"],
        r#"(require 'ivy)
  (unless (fboundp 'ivy-mode) (error "ivy-mode not defined"))
  (unless (fboundp 'ivy-read) (error "ivy-read not defined"))
  (princ "IVY-OK")"#,
    )
    .expect("install + use ivy");
    assert!(out.contains("IVY-OK"), "stdout:\n{out}");
}

/// Autoloads generated by `package-install` must make commands available after
/// `package-initialize` WITHOUT an explicit `require` — the real-user
/// expectation, matching GNU Emacs.
#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn install_which_key_autoloads_command_without_require() {
    let out = install_and_eval(
        &["which-key"],
        r#"(unless (fboundp 'which-key-mode)
    (error "which-key-mode not autoloaded after package-install (no require)"))
  (unless (fboundp 'which-key-add-key-based-replacements)
    (error "which-key-add-key-based-replacements not autoloaded"))
  (princ "WHICH-KEY-OK")"#,
    )
    .expect("install which-key (autoloads)");
    assert!(out.contains("WHICH-KEY-OK"), "stdout:\n{out}");
}

#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn install_flycheck_mode_available() {
    let out = install_and_eval(
        &["flycheck"],
        r#"(unless (fboundp 'flycheck-mode)
    (error "flycheck-mode not autoloaded after package-install"))
  (unless (fboundp 'global-flycheck-mode)
    (error "global-flycheck-mode not autoloaded"))
  (princ "FLYCHECK-OK")"#,
    )
    .expect("install flycheck");
    assert!(out.contains("FLYCHECK-OK"), "stdout:\n{out}");
}

#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn install_projectile_mode_available() {
    let out = install_and_eval(
        &["projectile"],
        r#"(unless (fboundp 'projectile-mode)
    (error "projectile-mode not autoloaded after package-install"))
  (unless (fboundp 'projectile-find-file)
    (error "projectile-find-file not autoloaded"))
  (princ "PROJECTILE-OK")"#,
    )
    .expect("install projectile");
    assert!(out.contains("PROJECTILE-OK"), "stdout:\n{out}");
}

// ---------------------------------------------------------------------------
// Standalone real-user-workflow scripts (drive package-install from `.el`),
// documenting the exact `M-x package-install` flow.
// ---------------------------------------------------------------------------

#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn real_user_workflow_install_dash_via_package_install() {
    let home = fresh_home();
    let script = elisp_script("real-user-workflow-dash.el");
    run_neomacs_script_ok(home.path(), &script).expect("real-user package-install dash");
}

#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn real_user_workflow_autoloads_available_after_package_initialize() {
    let home = fresh_home();
    let script = elisp_script("real-user-workflow-autoloads.el");
    run_neomacs_script_ok(home.path(), &script).expect("real-user autoloads after install");
}

#[test]
#[ignore = "network: installs a real package from MELPA via package-install"]
fn real_user_workflow_dependency_resolution() {
    let home = fresh_home();
    let script = elisp_script("real-user-workflow-dependency.el");
    run_neomacs_script_ok(home.path(), &script).expect("real-user dependency resolution");
}

// Keep the marker referenced so the shared reason string is never stale-linted.
#[allow(dead_code)]
const _NET_REASON: &str = NET;
