(run-at-time 0 nil (lambda ()
  (let* ((root (expand-file-name default-directory))
         (log (expand-file-name "tmp/reval/lat3.out" root))
         (done (expand-file-name "tmp/reval/lat3.done" root))
         (file (expand-file-name "lisp/emacs-lisp/cl-macs.el" root))
         (buf (find-file-noselect file))
         (n (string-to-number (or (getenv "LAT_ITERS") "20"))))
    (set-window-buffer (selected-window) buf)
    (with-current-buffer buf
      (emacs-lisp-mode)
      (font-lock-set-defaults)
      (goto-char (point-min))
      (let ((t0 (car (current-cpu-time))))
        (redisplay t)
        (write-region (format "first_redisplay_us=%d\n" (- (car (current-cpu-time)) t0)) nil log t 'silent))
      (let ((t0 (car (current-cpu-time))))
        (dotimes (_ n)
          (forward-line 3) (insert "x") (redisplay t)
          (delete-char -1) (redisplay t))
        (write-region (format "loop_us=%d iters=%d per_iter_us=%d\n"
                              (- (car (current-cpu-time)) t0) n
                              (/ (- (car (current-cpu-time)) t0) (max 1 n)))
                      nil log t 'silent)))
    (write-region "done\n" nil done nil 'silent)
    (kill-emacs 0))))
