//! Placeholder for buffer.c Rust rewrite module.
//!
//! Buffer operations are already dispatched via builtins.rs and
//! the buffer/ directory. This module will hold dedicated
//! implementations as they are extracted from the monolithic dispatcher.

/// Register this module's subrs. GNU: `syms_of_buffer` in `src/buffer.c`.
/// Extracted verbatim from the former flat `builtins::init_builtins`.
pub(crate) fn syms_of_buffer(ctx: &mut crate::emacs_core::eval::Context) {
    ctx.defsubr(
        "get-buffer-create",
        crate::emacs_core::builtins::buffers::builtin_get_buffer_create,
        1,
        Some(2),
    );
    ctx.defsubr(
        "get-buffer",
        crate::emacs_core::builtins::buffers::builtin_get_buffer,
        1,
        Some(1),
    );
    crate::emacs_core::builtins::register_builtin(
        ctx,
        crate::emacs_core::builtins::BuiltinRegistration::requires_eval_state(
            "make-indirect-buffer",
            crate::emacs_core::builtins::buffers::builtin_make_indirect_buffer,
            2,
            Some(4),
        ),
    );
    ctx.defsubr(
        "find-buffer",
        crate::emacs_core::builtins::buffers::builtin_find_buffer,
        2,
        Some(2),
    );
    ctx.defsubr(
        "buffer-live-p",
        crate::emacs_core::builtins::buffers::builtin_buffer_live_p,
        1,
        Some(1),
    );
    ctx.defsubr(
        "barf-if-buffer-read-only",
        crate::emacs_core::builtins::misc_eval::builtin_barf_if_buffer_read_only,
        0,
        Some(1),
    );
    ctx.defsubr(
        "bury-buffer-internal",
        crate::emacs_core::builtins::misc_eval::builtin_bury_buffer_internal,
        1,
        Some(1),
    );
    ctx.defsubr(
        "get-file-buffer",
        crate::emacs_core::builtins::buffers::builtin_get_file_buffer,
        1,
        Some(1),
    );
    ctx.defsubr(
        "kill-buffer",
        crate::emacs_core::builtins::buffers::builtin_kill_buffer,
        0,
        Some(1),
    );
    ctx.defsubr(
        "set-buffer",
        crate::emacs_core::builtins::buffers::builtin_set_buffer,
        1,
        Some(1),
    );
    ctx.defsubr(
        "current-buffer",
        crate::emacs_core::builtins::buffers::builtin_current_buffer,
        0,
        Some(0),
    );
    ctx.defsubr(
        "buffer-name",
        crate::emacs_core::builtins::buffers::builtin_buffer_name,
        0,
        Some(1),
    );
    ctx.defsubr(
        "buffer-file-name",
        crate::emacs_core::builtins::buffers::builtin_buffer_file_name,
        0,
        Some(1),
    );
    ctx.defsubr(
        "buffer-base-buffer",
        crate::emacs_core::builtins::buffers::builtin_buffer_base_buffer,
        0,
        Some(1),
    );
    ctx.defsubr(
        "buffer-last-name",
        crate::emacs_core::builtins::buffers::builtin_buffer_last_name,
        0,
        Some(1),
    );
    ctx.defsubr(
        "rename-buffer",
        crate::emacs_core::builtins::symbols::builtin_rename_buffer,
        1,
        Some(2),
    );
    crate::emacs_core::builtins::register_builtin(
        ctx,
        crate::emacs_core::builtins::BuiltinRegistration::requires_eval_state(
            "set-buffer-multibyte",
            crate::emacs_core::builtins::buffers::builtin_set_buffer_multibyte,
            1,
            Some(1),
        ),
    );
    crate::emacs_core::builtins::register_builtin(
        ctx,
        crate::emacs_core::builtins::BuiltinRegistration::requires_eval_state(
            "kill-all-local-variables",
            crate::emacs_core::builtins::buffers::builtin_kill_all_local_variables,
            0,
            Some(1),
        ),
    );
    ctx.defsubr(
        "buffer-swap-text",
        crate::emacs_core::builtins::buffers::builtin_buffer_swap_text,
        1,
        Some(1),
    );
    ctx.defsubr(
        "delete-all-overlays",
        crate::emacs_core::builtins::buffers::builtin_delete_all_overlays,
        0,
        Some(1),
    );
    ctx.defsubr(
        "erase-buffer",
        super::editfns::builtin_erase_buffer,
        0,
        Some(0),
    );
    ctx.defsubr(
        "buffer-enable-undo",
        crate::emacs_core::builtins::buffers::builtin_buffer_enable_undo,
        0,
        Some(1),
    );
    ctx.defsubr(
        "buffer-modified-p",
        crate::emacs_core::builtins::buffers::builtin_buffer_modified_p,
        0,
        Some(1),
    );
    ctx.defsubr(
        "set-buffer-modified-p",
        crate::emacs_core::builtins::buffers::builtin_set_buffer_modified_p,
        1,
        Some(1),
    );
    ctx.defsubr(
        "buffer-modified-tick",
        crate::emacs_core::builtins::buffers::builtin_buffer_modified_tick,
        0,
        None,
    );
    ctx.defsubr(
        "buffer-chars-modified-tick",
        crate::emacs_core::builtins::buffers::builtin_buffer_chars_modified_tick,
        0,
        None,
    );
    ctx.defsubr(
        "buffer-list",
        crate::emacs_core::builtins::buffers::builtin_buffer_list,
        0,
        Some(1),
    );
    ctx.defsubr(
        "other-buffer",
        crate::emacs_core::builtins::buffers::builtin_other_buffer,
        0,
        Some(3),
    );
    ctx.defsubr(
        "generate-new-buffer-name",
        crate::emacs_core::builtins::buffers::builtin_generate_new_buffer_name,
        1,
        Some(2),
    );
    ctx.defsubr(
        "buffer-local-value",
        crate::emacs_core::builtins::buffers::builtin_buffer_local_value,
        2,
        Some(2),
    );
    ctx.defsubr(
        "next-overlay-change",
        super::textprop::builtin_next_overlay_change,
        1,
        Some(1),
    );
    ctx.defsubr(
        "previous-overlay-change",
        super::textprop::builtin_previous_overlay_change,
        1,
        Some(1),
    );
    ctx.defsubr(
        "make-overlay",
        super::textprop::builtin_make_overlay,
        2,
        Some(5),
    );
    ctx.defsubr(
        "delete-overlay",
        super::textprop::builtin_delete_overlay,
        1,
        Some(1),
    );
    ctx.defsubr(
        "overlay-put",
        super::textprop::builtin_overlay_put,
        3,
        Some(3),
    );
    ctx.defsubr(
        "overlay-get",
        super::textprop::builtin_overlay_get,
        2,
        Some(2),
    );
    ctx.defsubr(
        "overlays-at",
        super::textprop::builtin_overlays_at,
        1,
        Some(2),
    );
    ctx.defsubr(
        "overlays-in",
        super::textprop::builtin_overlays_in,
        2,
        Some(2),
    );
    ctx.defsubr(
        "move-overlay",
        super::textprop::builtin_move_overlay,
        3,
        Some(4),
    );
    ctx.defsubr(
        "overlay-start",
        super::textprop::builtin_overlay_start,
        1,
        Some(1),
    );
    ctx.defsubr(
        "overlay-end",
        super::textprop::builtin_overlay_end,
        1,
        Some(1),
    );
    ctx.defsubr(
        "overlay-buffer",
        super::textprop::builtin_overlay_buffer,
        1,
        Some(1),
    );
    ctx.defsubr(
        "overlay-properties",
        super::textprop::builtin_overlay_properties,
        1,
        Some(1),
    );
    ctx.defsubr("overlayp", super::textprop::builtin_overlayp, 1, Some(1));
    ctx.defsubr(
        "buffer-local-variables",
        super::custom::builtin_buffer_local_variables,
        0,
        None,
    );
    ctx.defsubr(
        "force-mode-line-update",
        |ctx, args| {
            crate::emacs_core::builtins::misc_pure::builtin_force_mode_line_update(ctx, args)
        },
        0,
        Some(1),
    );
    ctx.defsubr(
        "get-truename-buffer",
        |_ctx, args| super::fileio::builtin_get_truename_buffer(args),
        1,
        Some(1),
    );
    ctx.defsubr(
        "internal--set-buffer-modified-tick",
        |ctx, args| {
            crate::emacs_core::builtins::buffers::builtin_internal_set_buffer_modified_tick(
                ctx, args,
            )
        },
        1,
        Some(2),
    );
    ctx.defsubr(
        "overlay-lists",
        super::textprop::builtin_overlay_lists,
        0,
        Some(0),
    );
    ctx.defsubr(
        "overlay-recenter",
        super::textprop::builtin_overlay_recenter,
        1,
        Some(1),
    );
    ctx.defsubr(
        "restore-buffer-modified-p",
        crate::emacs_core::builtins::buffers::builtin_restore_buffer_modified_p,
        1,
        Some(1),
    );
    ctx.defsubr(
        "set-buffer-major-mode",
        crate::emacs_core::builtins::symbols::builtin_set_buffer_major_mode,
        1,
        Some(1),
    );
    ctx.defsubr(
        "overlay-tree",
        |_ctx, args| crate::emacs_core::builtins::stubs::builtin_overlay_tree(args),
        0,
        Some(1),
    );
}
