#!/usr/bin/env python3
"""Extract GNU Emacs `DEFVAR_LISP' / `DEFVAR_KBOARD' declarations into Rust.

Companion to `extract_gnu_defvar_docs.py', which takes the doc: text of every
DEFVAR.  This one takes the *other* half of the declaration: the fact that GNU
declared the name in C at all, and which `Lisp_Fwd' variant that gives the
symbol.

    DEFVAR_LISP      ("name", Vsym, doc: ...)  ->  Lisp_Fwd_Obj
    DEFVAR_LISP_NOPRO("name", Vsym, doc: ...)  ->  Lisp_Fwd_Obj
    DEFVAR_KBOARD    ("name", field, doc: ...) ->  Lisp_Fwd_Kboard_Obj

Both macros set `redirect = SYMBOL_FORWARDED' (`src/lread.c:5275' and
`src/lread.c:5296'), which is what `set_internal' consults when it refuses an
unbind (`src/data.c:1802-1809'), what `Fdefvaralias' consults when it refuses a
built-in variable as a new alias (`src/eval.c:665-668'), and what
`Fmake_local_variable' consults when it refuses a keyboard variable
(`src/data.c:2287-2290').

DEFVAR_INT / DEFVAR_BOOL / DEFVAR_PER_BUFFER are deliberately NOT emitted: this
port already declares those through `defvar_bool.rs',
`Obarray::define_int_variable' and `BUFFER_SLOT_INFO' respectively.

Usage:
    scripts/extract_gnu_defvar_object_names.py \\
        --gnu-src /path/to/emacs-mirror/emacs/src \\
        --output  neovm-core/src/emacs_core/defvar_object/gnu_table.rs
"""

import argparse
import re
import sys
from pathlib import Path

DECL = re.compile(
    r'\bDEFVAR_(LISP_NOPRO|LISP|KBOARD)\s*\(\s*"([^"]+)"',
)

KIND = {
    "LISP": "Global",
    "LISP_NOPRO": "Global",
    "KBOARD": "Keyboard",
}


def collect(src: Path):
    """name -> (kind, "file:line"), keeping the first declaration seen."""
    found = {}
    for path in sorted(src.glob("*.c")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in DECL.finditer(text):
            macro, name = match.group(1), match.group(2)
            if name in found:
                continue
            line = text.count("\n", 0, match.start()) + 1
            found[name] = (KIND[macro], f"{path.name}:{line}")
    return found


HEADER = '''\
// AUTO-GENERATED by scripts/extract_gnu_defvar_object_names.py -- DO NOT EDIT.
//
// Source: GNU Emacs `src/*.c` DEFVAR_LISP / DEFVAR_LISP_NOPRO / DEFVAR_KBOARD
// declarations.  Re-run the extractor against an updated GNU mirror to
// refresh.  Each row is a name GNU's C declares, so the symbol is
// `SYMBOL_FORWARDED` there; the trailing comment is the GNU `file:line`.
//
// The table is the DECLARATION, not a measurement of this port: a name whose
// C file this build does not compile is still listed, and
// `adopt_gnu_object_forwarders` simply finds no symbol to adopt.

use super::{GnuObjectForward, GnuObjectVariable};

use GnuObjectForward::Global as G;
use GnuObjectForward::Keyboard as K;

#[rustfmt::skip]
pub(crate) static GNU_OBJECT_VARIABLES: &[GnuObjectVariable] = &[
'''

FOOTER = "];\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--gnu-src", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    args = ap.parse_args()

    found = collect(args.gnu_src)
    rows = []
    for name in sorted(found):
        kind, site = found[name]
        short = "G" if kind == "Global" else "K"
        rows.append(
            f'    GnuObjectVariable {{ name: r#"{name}"#, kind: {short} }}, // {site}\n'
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(HEADER + "".join(rows) + FOOTER, encoding="utf-8")

    globals_n = sum(1 for k, _ in found.values() if k == "Global")
    kboard_n = sum(1 for k, _ in found.values() if k == "Keyboard")
    print(f"{len(found)} names ({globals_n} Lisp_Objfwd, {kboard_n} Lisp_Kboard_Objfwd)"
          f" -> {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
